package=co.com.crediya
systemProp.version=3.24.0
reactive=true
lombok=true
metrics=true
language=java
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.integrity-check=true
systemProp.sonar.gradle.skipCompile=true
lombokVersion=1.18.30
springBootVersion=3.5.4
jacocoVersion=0.8.8
